local gears = require("gears")

-- load colors from pywal cache

local cache_dir = gears.filesystem.get_xdg_cache_home()
local wal = read_json(cache_dir.."wal/colors.json")

-- TODO: colors generated by wal only work perfectly for terminal
local color = {
    bg1     = wal["colors"]["color0"],
    bg2     = wal["colors"]["color1"],
    bg3     = wal["colors"]["color2"],
    bg4     = wal["colors"]["color3"],
    fg1     = wal["colors"]["color4"],
    fg2     = wal["colors"]["color5"],
    fg3     = wal["colors"]["color6"],
    fg4     = wal["colors"]["color7"],
    red     = wal["colors"]["color8"],
    orange  = wal["colors"]["color9"],
    yellow  = wal["colors"]["color10"],
    green   = wal["colors"]["color11"],
    cyan    = wal["colors"]["color12"],
    blue    = wal["colors"]["color13"],
    magenta = wal["colors"]["color14"],
    pink    = wal["colors"]["color15"],
}

local mods = {}
mods.wallpaper = wal["wallpaper"]

return {
    color = color,
    mods = mods,
}
