local gears = require("gears")

-- load colors from pywal cache

local cache_dir = gears.filesystem.get_xdg_cache_home()
local wal = read_json(cache_dir.."wal/colors.json")

-- TODO: colors generated by wal only work perfectly for terminal
local color = {
    wal["colors"]["color0"],
    wal["colors"]["color1"],
    wal["colors"]["color2"],
    wal["colors"]["color3"],
    wal["colors"]["color4"],
    wal["colors"]["color5"],
    wal["colors"]["color6"],
    wal["colors"]["color7"],
    wal["colors"]["color8"],
    wal["colors"]["color9"],
    wal["colors"]["color10"],
    wal["colors"]["color11"],
    wal["colors"]["color12"],
    wal["colors"]["color13"],
    wal["colors"]["color14"],
    wal["colors"]["color15"],
}

local mods = {}
mods.wallpaper = wal["wallpaper"]

return {
    color = color,
    mods = mods,
}
